name: Publish to pub.dev

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: '{{version}}'

jobs:
  publish:
    name: 'Publish to pub.dev'
    environment: pub.dev
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      # Minimal package setup and dry run checks.
      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ inputs.working-directory }}
      - name: Publish - dry run
        run: flutter pub publish --dry-run
        working-directory: ${{ inputs.working-directory }}
      # Publishing...
      - name: Publish to pub.dev
        run: flutter pub publish --force
        working-directory: ${{ inputs.working-directory }}